export const FETCH_USERS = `FETCH_USERS`
export const FETCH_USERS_SUCCESS = `FETCH_USERS_SUCCESS`
export const FETCH_USERS_ERROR = `FETCH_USERS_ERROR`

export const TABLE_CHANGE_OFFSET = `TABLE_CHANGE_OFFSET`

export const SORT_CHANGE_TYPE = `SORT_CHANGE_TYPE`

export const FILTER_CHANGE = `FILTER_CHANGE`
export const FILTER_GLOBAL_CHANGE = `FILTER_GLOBAL_CHANGE`
