export const FETCH_USERS = `FETCH_USERS`
export const FETCH_USERS_SUCCESS = `FETCH_USERS_SUCCESS`
export const FETCH_USERS_ERROR = `FETCH_USERS_ERROR`
export const DELETE_USERS = `DELETE_USERS`
export const SELECT_ALL_USERS = `SELECT_ALL_USERS`

export const TABLE_CHANGE_OFFSET = `TABLE_CHANGE_OFFSET`
export const TABLE_SELECT_ALL = `TABLE_SELECT_ALL`
export const TABLE_DESELECT_ALL = `TABLE_DESELECT_ALL`

export const SORT_CHANGE_TYPE = `SORT_CHANGE_TYPE`
export const SORT_MULTIPLE_CHANGE_TYPE = `SORT_MULTIPLE_CHANGE_TYPE`

export const FILTER_CHANGE = `FILTER_CHANGE`
export const FILTER_FIELD_CHANGE = `FILTER_FIELD_CHANGE`
export const FILTER_SEARCH_CHANGE = `FILTER_SEARCH_CHANGE`
export const FILTER_ENUM_CHANGE = `FILTER_ENUM_CHANGE`
export const FILTER_TOGGLE_CHANGE = `FILTER_TOGGLE_CHANGE`
export const FILTER_CLEAR = `FILTER_CLEAR`

export const SETTINGS_VIRTUALIZATION = `SETTINGS_VIRTUALIZATION`
export const SETTINGS_TABLE_COLUMNS = `SETTINGS_TABLE_COLUMNS`
